# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' Evaluate a cluster according to average distance divided by total profit
#'
#' @param zone A numeric vector of the id's included in the zone
#' @param inst A data.matrix of the instance contatining the columns id, x, y, score. Row number should coincide with point id.
#' @export
cluster_eval_cpp <- function(zone, inst) {
    .Call('_dz_cluster_eval_cpp', PACKAGE = 'dz', zone, inst)
}

